stages:
  - package

amd64:
 stage: package
 tags:
  - debian
 only:
  - tags
 script:
  - export NAME=add-kvm-guest
  - export VERSION=${CI_NAME_TAG}
  - export PKG=${NAME}_${VERSION}_all
  - cd source
  - make
  - /usr/sbin/reprepro-uploader ${PKG}.deb jessie stretch buster
  - rm -fv ${PKG}.deb
