#! /bin/bash

#########################################################
#							#
#	Copyright 2021					#
#							#
#	Author: Michal Skrha <michal@skrha.cz>		#
#							#
#########################################################

#
#	Read configuration file
#
CONFIG='/etc/default/add-kvm-guest'
[ ! -r ${CONFIG} ] && echo "Configuration file ${CONFIG} not readable!" && exit 1 || source ${CONFIG}

echo 'KVM guest installer, version BUILD_VERSION'

echo

#
#	Choose type of installation
#
echo 'Select type of installation:'
echo -e '\t0: Debian with preseed (default)'
echo -e '\t1: Custom ISO'
read inst
if [ "${inst}" == '' ]; then inst=0; fi
case ${inst} in
0)	# Debian with preseed
	echo 'Available Debian versions:'
	versions=(${!DEBIAN_DISTS[@]})
	for d in ${!DEBIAN_NAMES[@]}; do
		if [ ${d} -lt 10 ]; then
			dd=" ${d}"
		else
			dd=${d}
		fi
		if [ ${d} -eq ${versions[-1]} ]; then
			mm=' (default)'
		fi
		echo -e "\t${dd}: ${DEBIAN_NAMES[${d}]}${mm}"
	done
	read deb
	if [ "${deb}" == '' ]; then deb=${versions[-1]}; fi
	if [ $(echo "${deb}" | sed 's/[0-9]*//g' | wc -c) -ne 1 ]; then
		echo 'Invalid input (must contain only numbers)'
		exit
	fi
	if [ ${deb} -lt ${versions[0]} -o ${deb} -gt ${versions[-1]} ]; then
		echo 'Wrong Debian version!'
		exit
	fi
	preseed="${DEBIAN_PRESEED_PATH}/${DEBIAN_PRESEED_FILES[${deb}]}"
	msg1="Debian with preseed (${preseed})"
	msg2="Debian version:    ${DEBIAN_NAMES[${deb}]} (${deb})"
	;;
1)	# Custom ISO
	echo 'Available installation ISOs:'
	images=($(ls -1 ${ISO_BASE}))
	for k in ${!images[@]}; do echo "${k}: ${images[${k}]}"; done
	echo -n 'Select install ISO: '; read img
	if [ "x${img}" == 'x' ]; then
		echo 'No installation ISO chosen'
		exit
	fi
	if [ $(echo "${img}" | sed 's/[0-9]*//g' | wc -c) -ne 1 ]; then
		echo 'Invalid input (must contain only numbers)'
		exit
	fi
	if [ ${img} -lt 0 -o ${img} -ge ${#images[@]} ]; then
		echo 'Index out of range'
		exit
	fi
	iso="${ISO_BASE}${images[${img}]}"
	msg1='Custom ISO'
	msg2="Installation ISO:  ${iso}"
	;;
*)	# None
	echo 'Wrong installation type!'
	exit
	;;
esac

#
#	Guest name
#
echo
echo -n 'Name: '; read name
if [ "x${name}" == 'x' ]; then
	echo 'Guest name must not be empty'
	exit
fi
if [ $(echo "${name}" | sed 's/[a-zA-Z0-9_-]*//g' | wc -c) -ne 1 ]; then
	echo 'Invalid input (must contain only a-z A-Z 0-9 _ -)'
	exit
fi
if [ $(echo ${name} | wc -c) -gt 65 ]; then
	echo 'Guest name must have maximum 64 chars'
	exit
fi
# Check if guest with this name alredy exists
virsh domid ${name} >/dev/null 2>/dev/null
if [ ${?} -eq 0 ]; then
	echo "Guest with name ${name} alredy exists"
	exit
fi

#
#	Guest amount of RAM
#
echo -n 'RAM (MB) (default 512 MB): '; read ram
if [ "${ram}" == '' ]; then ram=512; fi
if [ $(echo "${ram}" | sed 's/[0-9]*//g' | wc -c) -ne 1 ]; then
	echo 'Invalid input (must contain only numbers)'
	exit
fi
if [ ${ram} -lt 64 -o ${ram} -gt 4096 ]; then
	echo 'RAM must be in range 64MB to 4096MB'
	exit
fi

#
#	Guest CPU cores
#
echo -n 'CPUs (default 1): '; read cpu
if [ "${cpu}" == '' ]; then cpu=1; fi
if [ $(echo "${cpu}" | sed 's/[0-9]*//g' | wc -c) -ne 1 ]; then
	echo 'Invalid input (must contain only numbers)'
	exit
fi
if [ ${cpu} -lt 1 -o ${cpu} -gt ${CPU_TOTAL} ]; then
	echo "CPUs must be in range 1 to ${CPU_TOTAL}"
	exit
fi

#
#	Guest primary (system) storage LVM volume group
#
case ${#VG_NAMES[@]} in
0)
	echo 'No LVM volume groups defined!'
	exit
	;;
1)
	vg=${VG_NAMES[0]}
	;;
*)
	echo
	echo 'LVM volume group:'
	for v in ${!VG_NAMES[@]}; do
		if [ ${v} -eq 0 ]; then
			mm=' (default)'
		fi
		echo -e "\t${v}: ${VG_NAMES[${v}]}${mm}"
	done
	read stor
	if [ "${stor}" == '' ]; then stor=0; fi
	if [ $(echo "${stor}" | sed 's/[0-9]*//g' | wc -c) -ne 1 ]; then
		echo 'Invalid input (must contain only numbers)'
		exit
	fi
	if [ ${stor} -lt 0 -o ${stor} -ge ${#VG_NAMES[@]} ]; then
		echo 'Index out of range'
		exit
	fi
	vg=${VG_NAMES[${stor}]}
	;;
esac
lv="${name}-root"
dev="/dev/${vg}/${lv}"

if [ -L ${dev} ]; then
	echo "Device ${dev} alredy exists"
	exit
fi

#
#	Guest primary (system) storage size
#
echo
echo -n 'Storage size (GB) (default 2 GB): '
read size
if [ "${size}" == '' ]; then size=2; fi
if [ $(echo "${size}" | sed 's/[0-9]*//g' | wc -c) -ne 1 ]; then
	echo 'Invalid input (must contain only numbers)'
	exit
fi
if [ ${size} -lt 1 -o ${size} -gt 512 ]; then
	echo 'Storage size must be in range 1 GB to 512 GB'
	exit
fi

#
#	Find lowest available port for VNC console
#
ports=$(grep vnc /etc/libvirt/qemu/*.xml 2>/dev/null)
if [ ${?} -ne 0 ]; then
	vnc=5900
else
	used=$(echo "${ports}" | sed 's/.*port=.\([0-9]\+\).*/\1/' | sort -n)
	for vnc in {5900..5999}; do
		echo "${used}" | grep ^${vnc}$ >/dev/null 2>/dev/null
		if [ ${?} -eq 1 ]; then break; fi
	done
fi

#
#	Print summary information how will be guest created
#
cat <<- EOF

	==============================
	Name: ${name}

	Memory:    ${ram} MB
	CPU cores: ${cpu}
	Storage:   ${dev} (${size} GB)

	Installation type: ${msg1}
	${msg2}

	VNC port: ${vnc}
	==============================

EOF

#
#	Ready to deploy?
#
echo -n 'Deploy? [Y/n]'; read -n 1 -s q
echo
if [ ${q:-Y} == 'n' ]; then exit; fi
echo

#
#	Create LVM logical volume
#
lvcreate -L "${size}g" -n ${lv} ${vg} || exit

#
#	Prepare arguments for virt-install by selected installation type
#
case ${inst} in
0)
	args="--location http://ftp.cz.debian.org/debian/dists/${DEBIAN_DISTS[${deb}]}/main/installer-amd64/ --extra-args auto=true --extra-args url=${preseed} --extra-args hostname=${name} --extra-args domain=${DOMAIN}"
	;;
1)
	args="--cdrom ${iso}"
	;;
*)
	echo 'BUG BUG BUG'
	exit 1
	;;
esac

#
#	Start the installation
#
virt-install \
	--virt-type=kvm \
	--name ${name} \
	--memory ${ram} \
	--vcpus ${cpu} \
	--cpu host-model-only \
	--disk path=${dev},device=disk,bus=virtio \
	--network bridge=lan,model=virtio \
	--graphics vnc,listen=${VNC_LISTEN},port=${vnc} \
	--noautoconsole \
	--noreboot \
	${args}
